# Generated by Django 4.0.8 on 2024-08-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_basket_item',
            field=models.BooleanField(default=False),
        ),
    ]
